### ISSUE TITLE
 [Adjustment] Mouse middle scroll on titlebar, keep focus, when window shading

### ISSUE THREAD

**Issue by samwhelp** [archcraft-os/archcraft-lxde#2]
> Mouse middle scroll on titlebar, **keep focus**, when window shading

I create a [sample](https://github.com/samwhelp/archcraft-adjustment/tree/main/sample/mousebind-adjustment/archcraft-lxde/2022-10-10/mouse_middle_scroll_on_titlebar_keep_focus_when_window_shading) for explaining this feature.

### context Titlebar / orginal

* [config snippet](https://github.com/samwhelp/archcraft-adjustment/tree/main/sample/mousebind-adjustment/archcraft-lxde/2022-10-10/mouse_middle_scroll_on_titlebar_keep_focus_when_window_shading/asset/orginal/lxde-rc.xml#L707-L716)

``` xml
  <mouse>
    <context name="Titlebar">

      <mousebind button="Up" action="Click">
        <action name="Shade"/>
        <action name="FocusToBottom"/>
        <action name="Unfocus"/>
        <action name="Lower"/>
      </mousebind>
      <mousebind button="Down" action="Click">
        <action name="Unshade"/>
        <action name="Raise"/>
      </mousebind>

    </context>
  </mouse>
```

### context Titlebar / adjust

* [config snippet](https://github.com/samwhelp/archcraft-adjustment/tree/main/sample/mousebind-adjustment/archcraft-lxde/2022-10-10/mouse_middle_scroll_on_titlebar_keep_focus_when_window_shading/lxde-rc.xml#L707-L718)

``` xml
  <mouse>
    <context name="Titlebar">

      <mousebind button="Up" action="Click">
        <action name="Shade"/>
        <!--
        <action name="FocusToBottom"/>
        <action name="Unfocus"/>
        <action name="Lower"/>
        //-->
      </mousebind>
      <mousebind button="Down" action="Click">
        <action name="Unshade"/>
        <action name="Raise"/>
      </mousebind>

    </context>
  </mouse>
```

## Link

* archcraft-openbox / [[Adjustment] Mouse middle scroll on titlebar, keep focus, when window shading](https://github.com/archcraft-os/archcraft-openbox/issues/12)
* archcraft-lxde / [all_enhance](https://github.com/samwhelp/archcraft-adjustment/tree/main/sample/mousebind-adjustment/archcraft-lxde/2022-10-10/all_enhance)

**Comment by adi1090x** [comment]
Subjective to user.
